// Authentication
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_AUTO_SIGNIN = 'AUTH_AUTO_SIGNIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Transactions
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_START = 'ADD_TRANSACTION_START';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAIL = 'ADD_TRANSACTION_FAIL';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_START = 'GET_TRANSACTIONS_START';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';

export const SEARCH_TRANSACTIONS = 'SEARCH_TRANSACTIONS';
export const SEARCH_TRANSACTIONS_START = 'SEARCH_TRANSACTIONS_START';
export const SEARCH_TRANSACTIONS_SUCCESS = 'SEARCH_TRANSACTIONS_SUCCESS';
export const SEARCH_TRANSACTIONS_FAIL = 'SEARCH_TRANSACTIONS_FAIL';

//Poojas
export const ADD_POOJA = 'ADD_POOJA';
export const ADD_POOJA_START = 'ADD_POOJA_START';
export const ADD_POOJA_SUCCESS = 'ADD_POOJA_SUCCESS';
export const ADD_POOJA_FAIL = 'ADD_POOJA_FAIL';

export const GET_POOJADETAILS = 'GET_POOJADETAILS';
export const GET_POOJADETAILS_START = 'GET_POOJADETAILS_START';
export const GET_POOJADETAILS_SUCCESS = 'GET_POOJADETAILS_SUCCESS';
export const GET_POOJADETAILS_FAIL = 'GET_POOJADETAILS_FAIL';
